In [2]:
import numpy as np

In [4]:
a = np.random.rand(1, 5, 2)
a.shape

(1, 5, 2)

In [11]:
c = [a, a, a]
c

[array([[[0.7871493 , 0.21133074],
         [0.1918383 , 0.13824629],
         [0.58951548, 0.50519847],
         [0.26934463, 0.91882698],
         [0.6863832 , 0.20011548]]]),
 array([[[0.7871493 , 0.21133074],
         [0.1918383 , 0.13824629],
         [0.58951548, 0.50519847],
         [0.26934463, 0.91882698],
         [0.6863832 , 0.20011548]]]),
 array([[[0.7871493 , 0.21133074],
         [0.1918383 , 0.13824629],
         [0.58951548, 0.50519847],
         [0.26934463, 0.91882698],
         [0.6863832 , 0.20011548]]])]

In [12]:
b =  np.concatenate(c, axis=0)
b.shape

(3, 5, 2)

In [8]:
b

array([[[0.7871493 , 0.21133074],
        [0.1918383 , 0.13824629],
        [0.58951548, 0.50519847],
        [0.26934463, 0.91882698],
        [0.6863832 , 0.20011548]],

       [[0.7871493 , 0.21133074],
        [0.1918383 , 0.13824629],
        [0.58951548, 0.50519847],
        [0.26934463, 0.91882698],
        [0.6863832 , 0.20011548]]])

In [ ]:
"""Generic encoder/decoder for any class with __init__ using __module__ and __class__."""

import json


class User:

    def __init__(self, name, age, active, balance, friends):
        self.name = name
        self.age = age
        self.active = active
        self.balance = balance
        self.friends = friends


class Player:

    def __init__(self, name, nickname, level):
        self.name = name
        self.nickname = nickname
        self.level = level


def encode_obj(obj):
    obj_dict = {"__class__": obj.__class__.__name__, "__module__": obj.__module__}
    obj_dict.update(obj.__dict__)
    return obj_dict


def decode_dct(dct):
    if "__class__" in dct:
        class_name = dct.pop("__class__")
        module_name = dct.pop("__module__")
        module = __import__(module_name)
        class_ = getattr(module, class_name)
        return class_(**dct)
    return dct

user = User("John", 28, True, 20.7, ["Jane", "Tom"])
user_json = json.dumps(user, default=encode_obj, indent=4)
print(user_json)
user_decoded = json.loads(user_json, object_hook=decode_dct)
print(type(user_decoded))

player = Player("Max", "max1234", 5)
player_json = json.dumps(player, default=encode_obj, indent=4)
print(player_json)
player_decoded = json.loads(player_json, object_hook=decode_dct)
print(type(player_decoded))

{
    "__class__": "User",
    "__module__": "__main__",
    "name": "John",
    "age": 28,
    "active": true,
    "balance": 20.7,
    "friends": [
        "Jane",
        "Tom"
    ]
}
<class '__main__.User'>
{
    "__class__": "Player",
    "__module__": "__main__",
    "name": "Max",
    "nickname": "max1234",
    "level": 5
}
<class '__main__.Player'>


In [22]:
a = [[1, 2, 3], [4, 5, 6]]

In [23]:

a += np.full((4, 3), -1).tolist()
a

[[1, 2, 3], [4, 5, 6], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1]]

In [10]:
np.full((5, 4), [640, 640, 1, 1], dtype=np.int32)

array([[640, 640,   1,   1],
       [640, 640,   1,   1],
       [640, 640,   1,   1],
       [640, 640,   1,   1],
       [640, 640,   1,   1]], dtype=int32)

In [11]:
import numpy as np

a = np.random.rand(4, 2)
a

array([[0.98592989, 0.88141205],
       [0.88248258, 0.8124161 ],
       [0.77698481, 0.75581196],
       [0.64478508, 0.03970559]])

In [12]:
a[:,0] = a[:,0] * 10 + 1

In [13]:
a

array([[10.85929887,  0.88141205],
       [ 9.82482582,  0.8124161 ],
       [ 8.76984813,  0.75581196],
       [ 7.44785076,  0.03970559]])